package chatmodule;


/**
* chatmodule/DialogueOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* mardi 26 janvier 2016 00 h 41 CET
*/

public interface DialogueOperations 
{
  String[] clients ();
  void clients (String[] newClients);
  String[] messages ();
  void messages (String[] newMessages);
  void connect (String pseudo);
  void disconnect (String pseudo);
  String[] getClients ();
  void sendMessage (String from, String to, String message);
  String[] getMessages (String pseudo);
} // interface DialogueOperations
