package chatmodule;

/**
* chatmodule/DialogueHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* mardi 26 janvier 2016 00 h 41 CET
*/

public final class DialogueHolder implements org.omg.CORBA.portable.Streamable
{
  public chatmodule.Dialogue value = null;

  public DialogueHolder ()
  {
  }

  public DialogueHolder (chatmodule.Dialogue initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = chatmodule.DialogueHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    chatmodule.DialogueHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return chatmodule.DialogueHelper.type ();
  }

}
