package chatmodule;


/**
* chatmodule/DialoguePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* mardi 26 janvier 2016 00 h 41 CET
*/

public abstract class DialoguePOA extends org.omg.PortableServer.Servant
 implements chatmodule.DialogueOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_clients", new java.lang.Integer (0));
    _methods.put ("_set_clients", new java.lang.Integer (1));
    _methods.put ("_get_messages", new java.lang.Integer (2));
    _methods.put ("_set_messages", new java.lang.Integer (3));
    _methods.put ("connect", new java.lang.Integer (4));
    _methods.put ("disconnect", new java.lang.Integer (5));
    _methods.put ("getClients", new java.lang.Integer (6));
    _methods.put ("sendMessage", new java.lang.Integer (7));
    _methods.put ("getMessages", new java.lang.Integer (8));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // chatmodule/Dialogue/_get_clients
       {
         String $result[] = null;
         $result = this.clients ();
         out = $rh.createReply();
         chatmodule.ClientsHelper.write (out, $result);
         break;
       }

       case 1:  // chatmodule/Dialogue/_set_clients
       {
         String newClients[] = chatmodule.ClientsHelper.read (in);
         this.clients (newClients);
         out = $rh.createReply();
         break;
       }

       case 2:  // chatmodule/Dialogue/_get_messages
       {
         String $result[] = null;
         $result = this.messages ();
         out = $rh.createReply();
         chatmodule.MessagesHelper.write (out, $result);
         break;
       }

       case 3:  // chatmodule/Dialogue/_set_messages
       {
         String newMessages[] = chatmodule.MessagesHelper.read (in);
         this.messages (newMessages);
         out = $rh.createReply();
         break;
       }

       case 4:  // chatmodule/Dialogue/connect
       {
         String pseudo = in.read_string ();
         this.connect (pseudo);
         out = $rh.createReply();
         break;
       }

       case 5:  // chatmodule/Dialogue/disconnect
       {
         String pseudo = in.read_string ();
         this.disconnect (pseudo);
         out = $rh.createReply();
         break;
       }

       case 6:  // chatmodule/Dialogue/getClients
       {
         String $result[] = null;
         $result = this.getClients ();
         out = $rh.createReply();
         chatmodule.ClientsHelper.write (out, $result);
         break;
       }

       case 7:  // chatmodule/Dialogue/sendMessage
       {
         String from = in.read_string ();
         String to = in.read_string ();
         String message = in.read_string ();
         this.sendMessage (from, to, message);
         out = $rh.createReply();
         break;
       }

       case 8:  // chatmodule/Dialogue/getMessages
       {
         String pseudo = in.read_string ();
         String $result[] = null;
         $result = this.getMessages (pseudo);
         out = $rh.createReply();
         chatmodule.MessagesHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:chatmodule/Dialogue:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Dialogue _this() 
  {
    return DialogueHelper.narrow(
    super._this_object());
  }

  public Dialogue _this(org.omg.CORBA.ORB orb) 
  {
    return DialogueHelper.narrow(
    super._this_object(orb));
  }


} // class DialoguePOA
