package chatmodule;


/**
* chatmodule/Message.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* mardi 26 janvier 2016 00 h 41 CET
*/

public final class Message implements org.omg.CORBA.portable.IDLEntity
{
  public String from = null;
  public String to = null;
  public String message = null;

  public Message ()
  {
  } // ctor

  public Message (String _from, String _to, String _message)
  {
    from = _from;
    to = _to;
    message = _message;
  } // ctor

} // class Message
