package chatmodule;

/**
* chatmodule/MessageHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* mardi 26 janvier 2016 00 h 41 CET
*/

public final class MessageHolder implements org.omg.CORBA.portable.Streamable
{
  public chatmodule.Message value = null;

  public MessageHolder ()
  {
  }

  public MessageHolder (chatmodule.Message initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = chatmodule.MessageHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    chatmodule.MessageHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return chatmodule.MessageHelper.type ();
  }

}
